pipeline {
    agent {
        docker {
            image 'python'
            args '-u root'
            reuseNode true
        }
    }
    stages {
        stage('Install Dependencies') {
            steps {
                sh 'pip install -r docs/requirements.txt'
            }
        }
        stage('Build') { 
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py' 
                stash(name: 'compiled-results', includes: 'sources/*.py*') 
            }
        }
        stage('Test') {
            steps {
                sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}
