pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile https://github.com/EHDEPELUCHE/Entregable3-VS/sources/add2vals.py https://github.com/EHDEPELUCHE/Entregable3-VS/sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-linux:python2'
                }
            }
            steps {
                sh 'pyinstaller --onefile https://github.com/EHDEPELUCHE/Entregable3-VS/sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'https://github.com/EHDEPELUCHE/Entregable3-VS/dist/add2vals'
                }
            }
        }
    }
}
